name: Deploy branch to XDN

on:
  push:
  release:
    types: [published]

jobs:
  dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [11.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
        node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Deploy to XDN
        run: npm run deploy --team=$TEAM --token=$TOKEN
