name: Deploy branch to XDN

on:
  push:
  release:
    types: [published]

jobs:
  dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [11.x]

    steps:
      - run: npm ci
      - name: Deploy to XDN
        run: npm run deploy --team=$TEAM --token=$TOKEN
