name: Deploy branch to XDN

on:
  push:
    branches: [ master ]

jobs:
  dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [11.x]
    steps:
      - run: xdn init
      - name: Deploy to XDN
        run: xdn deploy --team=nikhil-mahajan --token=Pk4fbb7tWjM8kYg1rHPqPjYi
